name: 'Workflow1'
description: 'Workflow1 description'
runner-type: 'cpu'
inputs:
  model-repository:
    description: 'Name of HuggingFace model repository (org/repository).'
    required: true
tasks:
  hf-to-gguf:
    name: Convert HuggingFace to GGUF
    uses: github.com/itaypodhajcer/task2@main
    runner-type: cpu
    args:
      out-model-type: auto
      in-model-path: /my/test/${{ inputs.model-repository }}
      out-model-path: $WORKFLOW_STORAGE/${{ inputs.model-repository }}/converted.gguf
  gguf-quantize:  
    name: Quantize GGUF to Q4_K_M
    uses: github.com/itaypodhajcer/task3@main
    runner-type: cpu
    depends-on: [ hf-to-gguf ]
    args:
      quantization-type: Q4_K_M
      in-model-path: $WORKFLOW_STORAGE/${{ inputs.model-repository }}/converted.gguf
      out-model-path: $WORKFLOW_STORAGE/${{ inputs.model-repository }}/quantized.gguf
